/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { GitProviderSettingWhereUniqueInput } from "../../gitProviderSetting/base/GitProviderSettingWhereUniqueInput";
import { ValidateNested, IsOptional, IsEnum } from "class-validator";
import { Type } from "class-transformer";
import { StringFilter } from "../../util/StringFilter";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { EnumGitSpaceProvider } from "./EnumGitSpaceProvider";
import { EnumGitSpaceSpaceType } from "./EnumGitSpaceSpaceType";
import { UserWhereUniqueInput } from "../../user/base/UserWhereUniqueInput";

@InputType()
class GitSpaceWhereInput {
  @ApiProperty({
    required: false,
    type: () => GitProviderSettingWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => GitProviderSettingWhereUniqueInput)
  @IsOptional()
  @Field(() => GitProviderSettingWhereUniqueInput, {
    nullable: true,
  })
  gitProviderSetting?: GitProviderSettingWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  name?: StringNullableFilter;

  @ApiProperty({
    required: false,
    enum: EnumGitSpaceProvider,
  })
  @IsEnum(EnumGitSpaceProvider)
  @IsOptional()
  @Field(() => EnumGitSpaceProvider, {
    nullable: true,
  })
  provider?: "GitHub" | "GitLab" | "Bitbucket";

  @ApiProperty({
    required: false,
    enum: EnumGitSpaceSpaceType,
  })
  @IsEnum(EnumGitSpaceSpaceType)
  @IsOptional()
  @Field(() => EnumGitSpaceSpaceType, {
    nullable: true,
  })
  spaceType?: "Organization" | "User";

  @ApiProperty({
    required: false,
    type: () => UserWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => UserWhereUniqueInput)
  @IsOptional()
  @Field(() => UserWhereUniqueInput, {
    nullable: true,
  })
  user?: UserWhereUniqueInput;
}

export { GitSpaceWhereInput as GitSpaceWhereInput };
