/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { CreateVariableArgs } from "./CreateVariableArgs";
import { UpdateVariableArgs } from "./UpdateVariableArgs";
import { DeleteVariableArgs } from "./DeleteVariableArgs";
import { VariableFindManyArgs } from "./VariableFindManyArgs";
import { VariableFindUniqueArgs } from "./VariableFindUniqueArgs";
import { Variable } from "./Variable";
import { VariableCategory } from "../../variableCategory/base/VariableCategory";
import { VariableService } from "../variable.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Variable)
export class VariableResolverBase {
  constructor(
    protected readonly service: VariableService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Variable",
    action: "read",
    possession: "any",
  })
  async _variablesMeta(
    @graphql.Args() args: VariableFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Variable])
  @nestAccessControl.UseRoles({
    resource: "Variable",
    action: "read",
    possession: "any",
  })
  async variables(
    @graphql.Args() args: VariableFindManyArgs
  ): Promise<Variable[]> {
    return this.service.findMany(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Variable, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Variable",
    action: "read",
    possession: "own",
  })
  async variable(
    @graphql.Args() args: VariableFindUniqueArgs
  ): Promise<Variable | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Variable)
  @nestAccessControl.UseRoles({
    resource: "Variable",
    action: "create",
    possession: "any",
  })
  async createVariable(
    @graphql.Args() args: CreateVariableArgs
  ): Promise<Variable> {
    return await this.service.create({
      ...args,
      data: {
        ...args.data,

        variableCategory: args.data.variableCategory
          ? {
              connect: args.data.variableCategory,
            }
          : undefined,
      },
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Variable)
  @nestAccessControl.UseRoles({
    resource: "Variable",
    action: "update",
    possession: "any",
  })
  async updateVariable(
    @graphql.Args() args: UpdateVariableArgs
  ): Promise<Variable | null> {
    try {
      return await this.service.update({
        ...args,
        data: {
          ...args.data,

          variableCategory: args.data.variableCategory
            ? {
                connect: args.data.variableCategory,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Variable)
  @nestAccessControl.UseRoles({
    resource: "Variable",
    action: "delete",
    possession: "any",
  })
  async deleteVariable(
    @graphql.Args() args: DeleteVariableArgs
  ): Promise<Variable | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => VariableCategory, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "VariableCategory",
    action: "read",
    possession: "any",
  })
  async variableCategory(
    @graphql.Parent() parent: Variable
  ): Promise<VariableCategory | null> {
    const result = await this.service.getVariableCategory(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
